-- Run once in the Supabase SQL Editor using the project owner account.
-- The Flask backend uses the Supabase secret/service-role key; browser roles
-- receive no direct access to portfolio or contact data.

create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description text,
    long_description text,
    technologies jsonb,
    project_type varchar(20) not null default 'web'
        check (project_type in ('web', 'mobile', 'desktop', 'data', 'design')),
    status varchar(20) not null default 'completed'
        check (status in ('completed', 'in_progress', 'planned')),
    featured boolean not null default false,
    image_url varchar(500),
    demo_url varchar(500),
    github_url varchar(500),
    case_study_url varchar(500),
    display_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique,
    description text,
    icon_svg text,
    color varchar(7) not null default '#6366f1',
    display_order integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.blog_posts (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    slug varchar(255) not null unique,
    excerpt text,
    content text not null,
    featured_image varchar(500),
    category varchar(100),
    tags jsonb not null default '[]'::jsonb,
    status varchar(20) not null default 'draft'
        check (status in ('draft', 'published', 'archived')),
    featured boolean not null default false,
    views integer not null default 0,
    reading_time integer not null default 5,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    published_at timestamptz
);

create table if not exists public.blog_categories (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique,
    slug varchar(100) not null unique,
    description text,
    color varchar(7) not null default '#4a9bff',
    created_at timestamptz not null default now()
);

create table if not exists public.blog_comments (
    id bigint generated by default as identity primary key,
    post_id bigint not null references public.blog_posts(id) on delete cascade,
    name varchar(100) not null,
    email varchar(255) not null,
    website varchar(255),
    content text not null,
    status varchar(20) not null default 'pending'
        check (status in ('pending', 'approved', 'spam')),
    created_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null,
    subject varchar(255) not null,
    message text not null,
    status varchar(20) not null default 'unread'
        check (status in ('unread', 'read', 'replied')),
    created_at timestamptz not null default now()
);

create table if not exists public.site_visits (
    id bigint generated by default as identity primary key,
    visit_count bigint not null default 0,
    last_updated timestamptz not null default now()
);

alter table public.projects enable row level security;
alter table public.categories enable row level security;
alter table public.blog_posts enable row level security;
alter table public.blog_categories enable row level security;
alter table public.blog_comments enable row level security;
alter table public.contact_messages enable row level security;
alter table public.site_visits enable row level security;

revoke all on table public.projects from public, anon, authenticated;
revoke all on table public.categories from public, anon, authenticated;
revoke all on table public.blog_posts from public, anon, authenticated;
revoke all on table public.blog_categories from public, anon, authenticated;
revoke all on table public.blog_comments from public, anon, authenticated;
revoke all on table public.contact_messages from public, anon, authenticated;
revoke all on table public.site_visits from public, anon, authenticated;

grant all privileges on table public.projects to service_role;
grant all privileges on table public.categories to service_role;
grant all privileges on table public.blog_posts to service_role;
grant all privileges on table public.blog_categories to service_role;
grant all privileges on table public.blog_comments to service_role;
grant all privileges on table public.contact_messages to service_role;
grant all privileges on table public.site_visits to service_role;

grant usage, select on sequence public.projects_id_seq to service_role;
grant usage, select on sequence public.categories_id_seq to service_role;
grant usage, select on sequence public.blog_posts_id_seq to service_role;
grant usage, select on sequence public.blog_categories_id_seq to service_role;
grant usage, select on sequence public.blog_comments_id_seq to service_role;
grant usage, select on sequence public.contact_messages_id_seq to service_role;
grant usage, select on sequence public.site_visits_id_seq to service_role;

-- CV content: single-row JSON document edited from the admin panel and
-- rendered by the public /cv page and the PDF download.
create table if not exists public.cv_content (
    id int primary key,
    data jsonb not null,
    updated_at timestamptz not null default now()
);

alter table public.cv_content enable row level security;
revoke all on table public.cv_content from public, anon, authenticated;
grant all privileges on table public.cv_content to service_role;
