#!/usr/bin/env python3
"""
Environment Setup Helper
Run this script to help set up your .env file with proper values
"""

import secrets
import os
from pathlib import Path

def generate_secret_key():
    """Generate a secure secret key"""
    return secrets.token_hex(32)

def setup_env_file():
    """Interactive setup for .env file"""
    print("🔧 Personal Portfolio Environment Setup")
    print("=" * 50)
    
    # Check if .env exists
    env_file = Path(".env")
    if env_file.exists():
        print("📁 Found existing .env file")
        backup = input("Create backup? (y/n): ").lower().strip()
        if backup == 'y':
            backup_name = ".env.backup"
            env_file.rename(backup_name)
            print(f"✅ Backup created: {backup_name}")
    
    print("\n🔑 Let's set up your credentials...")
    
    # Generate SECRET_KEY
    secret_key = generate_secret_key()
    print(f"\n✅ Generated SECRET_KEY: {secret_key}")
    
    # Get Supabase credentials
    print("\n📊 Supabase Configuration")
    print("Go to your Supabase project → Settings → API")
    
    supabase_url = input("Enter your Supabase URL (https://xxx.supabase.co): ").strip()
    if not supabase_url.startswith('https://'):
        supabase_url = f"https://{supabase_url}"
    
    supabase_key = input("Enter your Supabase anon key: ").strip()
    supabase_service_key = input("Enter your Supabase service_role key: ").strip()
    
    # Get admin credentials
    print("\n👤 Admin Configuration")
    admin_username = input("Choose admin username (default: admin): ").strip() or "admin"
    admin_password = input("Choose admin password (min 12 chars): ").strip()
    
    while len(admin_password) < 12:
        print("❌ Password too short! Must be at least 12 characters.")
        admin_password = input("Choose admin password (min 12 chars): ").strip()
    
    # Create .env content
    env_content = f"""# SECURITY WARNING: This file contains sensitive information
# Never commit this file to version control
# Generated by setup_env.py

# Database Configuration
DATABASE_TYPE=supabase

# MySQL Configuration (fallback/development)
MYSQL_HOST=127.0.0.1
MYSQL_USER=root
MYSQL_PASSWORD=Dhire12345@@
MYSQL_DATABASE=personal_portfolio

# Supabase Configuration
SUPABASE_URL={supabase_url}
SUPABASE_KEY={supabase_key}
SUPABASE_SERVICE_KEY={supabase_service_key}

# Application Security
SECRET_KEY={secret_key}
ADMIN_USERNAME={admin_username}
ADMIN_PASSWORD={admin_password}

# Security Settings
FLASK_ENV=production
FLASK_DEBUG=False
SSL_DISABLE=False
"""
    
    # Write .env file
    with open(".env", "w") as f:
        f.write(env_content)
    
    print("\n✅ .env file created successfully!")
    
    # Test the configuration
    print("\n🧪 Testing configuration...")
    try:
        from dotenv import load_dotenv
        load_dotenv()
        
        # Basic validation
        required_vars = ['DATABASE_TYPE', 'SUPABASE_URL', 'SUPABASE_KEY', 'SECRET_KEY', 'ADMIN_USERNAME', 'ADMIN_PASSWORD']
        missing = []
        
        for var in required_vars:
            if not os.getenv(var):
                missing.append(var)
        
        if missing:
            print(f"❌ Missing variables: {', '.join(missing)}")
        else:
            print("✅ All required variables are set!")
            
            # Test database connection
            print("\n🔍 Testing database connection...")
            try:
                import subprocess
                result = subprocess.run(['python', 'test_database.py'], 
                                      capture_output=True, text=True, timeout=30)
                
                if result.returncode == 0:
                    print("✅ Database connection test passed!")
                else:
                    print("❌ Database connection test failed:")
                    print(result.stdout)
                    print(result.stderr)
            except Exception as e:
                print(f"⚠️ Could not run database test: {e}")
                print("Run 'python test_database.py' manually to test")
    
    except ImportError:
        print("⚠️ python-dotenv not installed. Run: pip install python-dotenv")
    
    print("\n🎯 Next Steps:")
    print("1. Make sure you've run the SQL schema in Supabase")
    print("2. Run: python test_database.py")
    print("3. If tests pass, you're ready to deploy!")
    print("\n📚 See DEPLOYMENT_GUIDE.md for deployment instructions")

def show_supabase_instructions():
    """Show detailed Supabase setup instructions"""
    print("\n📊 Supabase Setup Instructions:")
    print("1. Go to https://supabase.com")
    print("2. Sign up/login and create a new project")
    print("3. Wait for project to be ready (2-3 minutes)")
    print("4. Go to Settings → API")
    print("5. Copy:")
    print("   - Project URL (https://xxx.supabase.co)")
    print("   - anon public key (long string starting with eyJ...)")
    print("   - service_role key (another long string)")
    print("6. Go to SQL Editor")
    print("7. Copy contents of supabase_schema.sql and run it")
    print("8. Come back here and run this script again")

if __name__ == "__main__":
    try:
        # Check if Supabase credentials are needed
        if len(os.sys.argv) > 1 and os.sys.argv[1] == "--supabase-help":
            show_supabase_instructions()
        else:
            setup_env_file()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
    except Exception as e:
        print(f"\n❌ Error during setup: {e}")
        print("Please check the SETUP_CREDENTIALS.md file for manual instructions")